# Generated by Django 5.0.6 on 2024-07-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='artist',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='ratingCount',
            new_name='RatingCount',
        ),
    ]
