# Generated by Django 5.0.6 on 2024-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0004_rename_artist_manga_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='Category',
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(default=None, related_name='bookmarked_users', to='MangaLib.manga'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(default=None, related_name='favourite_users', to='MangaLib.manga'),
        ),
        migrations.AddField(
            model_name='manga',
            name='Category',
            field=models.ManyToManyField(related_name='manga', to='MangaLib.category'),
        ),
    ]
