# Generated by Django 5.0.6 on 2024-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0005_remove_manga_category_alter_user_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Is_Finished',
            field=models.CharField(default=None),
        ),
    ]
