# Generated by Django 5.0.6 on 2024-07-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0006_alter_manga_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=-1993, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manga',
            name='Is_Finished',
            field=models.BooleanField(default=True),
        ),
    ]
