# Generated by Django 5.0.6 on 2024-08-15 22:16

import MangaLib.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0008_alter_manga_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Image',
            field=models.ImageField(default='image 8.png', upload_to=MangaLib.models.manga_cover_directory_path),
        ),
        migrations.AlterField(
            model_name='manga',
            name='Rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to=MangaLib.models.manga_pages_directory_path)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='MangaLib.manga')),
            ],
        ),
    ]
