# Generated by Django 5.0.6 on 2024-08-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0009_alter_manga_image_alter_manga_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='Is_Finished',
            new_name='Status',
        ),
    ]
