# Generated by Django 5.0.6 on 2024-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0011_mangapage_chapter_mangapage_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manga',
            name='Image',
            field=models.ImageField(default='image 8.png', upload_to='manga_covers/'),
        ),
    ]
