# Generated by Django 5.0.6 on 2024-08-18 17:11

import MangaLib.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0012_mangapage_page_number_alter_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Image',
            field=models.ImageField(default='Manga/image_10.png', upload_to=MangaLib.models.manga_cover_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='Users/User profile picture.png', upload_to=MangaLib.models.user_profile_image_directory_path),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
