# Generated by Django 5.0.6 on 2024-08-19 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0014_alter_mangapage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
