# Generated by Django 5.0.6 on 2024-08-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0015_manga_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Status',
            field=models.CharField(choices=[('completed', 'Завершен'), ('announced', 'Анонс'), ('paused', 'Приостановлен'), ('discontinued', 'Выпуск прекращен')], default='announced', max_length=32),
        ),
    ]
