# Generated by Django 5.0.6 on 2024-08-31 14:55

import MangaLib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0017_person_alter_manga_image_alter_manga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Publisher',
            field=models.CharField(default='PaulichP', max_length=64),
        ),
        migrations.AddField(
            model_name='manga',
            name='moderation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default='Persons/image.png', upload_to=MangaLib.models.person_image_directory_path),
        ),
    ]
