# Generated by Django 5.0.6 on 2024-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0019_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='moderation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
    ]
