# Generated by Django 5.0.6 on 2024-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0020_person_moderation_date_person_moderation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='moderation_date',
            new_name='Moderation_date',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='moderation_status',
            new_name='Moderation_status',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='moderation_date',
            new_name='Moderation_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='moderation_status',
            new_name='Moderation_status',
        ),
        migrations.AddField(
            model_name='manga',
            name='Mod_message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='Mod_message',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
