# Generated by Django 5.0.6 on 2024-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0021_rename_moderation_date_manga_moderation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Url_message',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
