# Generated by Django 5.0.6 on 2024-09-07 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangaLib', '0024_person_created_by_alter_manga_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
